### ISSUE TITLE
If an effect is used repeatedly but defined once, it happens once.

### ISSUE THREAD

**Issue by jessitron** [evancz/elm-effects#16]
Perhaps this is intentional or expected. However, it surprised me, so here's a report.

When I have an effect that is the same all the time, and define it as (for instance)

```readCookie : Effects Action
readCookie = // blah blah task passed to Effects.task```

and then return that effect from both init and update functions (using StartApp), it executes only during init, and never again.
Changing the type to 

```readCookie : () -> Effects Action```

causes the program to work, and the effect happens every time it's returned from update.
If this is unavoidable, then so be it. Scalaz tasks have the same problem. Er, behavior.
It bothers me because I want an Effect to be data, to be an instruction for the outside world, rather than something that causes a side effect on instantiation.

**Comment by evancz** [comment]
Can you show a minimal code example? It should be true that you can create a task and run it many times.

**Comment by jessitron** [comment]
Here's my example. Maybe it could be minimized further? but this has a bunch of diagnostic tools built in from when I tried to figure it out.

https://github.com/jessitron/try-elm-cookie/tree/example

make TryIt.elm
open index.html (in Firefox; chrome doesn't do cookies on file://)
open the dev console to see the prints
type in the box. it sets (and should read) the cookie after each letter.
The cookie gets read once (on init). Set is called repeatedly, and after each it's supposed to read too.
On init, it requests readCookie; after receiving SetOk (which it does, you can tell by the count increasing and by the console log) update also requests readCookie, but it never happens again.

**Comment by rgrempel** [comment]
One problem I see is with your src/Native/Cookie.js. You use F2 to define the `set` function, but (unless I'm missing something), the `set` function only takes 1 parameter. I tried removing the F2, so that it was:

```elm
  return localRuntime.Native.Cookie.values = {
    set: set,
    get: get
  };
```

and the results appeared to be more what you expected.

**Comment by rgrempel** [comment]
Also, here's another Elm module for dealing with cookies.

https://github.com/rgrempel/elm-cookies.git

**Comment by jessitron** [comment]
The F2 was indeed a problem, which threw a really nasty error later. But that is separate from the readCookies one, as it happened also when set took 2 arguments.

**Comment by jessitron** [comment]
@rgrempel I wish your library had been published already, so that I would not have written mine. :-(

**Comment by rgrempel** [comment]
The other possible problem with your code -- I'm not entirely sure about this -- is that your native functions are doing too much work at task creation time, as opposed to task execution time. 

What I mean by that is this. When your "get" and "set" functions are called, that is task creation time -- that is, this code executes once, when you create the task. So, it's not surprising that it doesn't execute again at task execution time -- how could it? All that happens at task execution time is that the Task.succeed or Task.fail that you've already constructed is used. So, you've basically created a Task that always returns a constant when executed. Which, of course, is not what you want.

In order to actually execute some code at task execution time, I think you need to use the native Task.asyncFunction, supplying the function to execute at task execution time. For an example, you can see how I did it in my version of this.

**Comment by evancz** [comment]
It sounds like this comes down to issues in the "native code" which is not really a public API. If you want to do asynchronous stuff, it is true that it must all be in `asyncFunction` to be properly wrapped up. I'm going to close this here, but lets reopen if we can definitively pin this to this library.

We have a couple community members (including Richard) doing native reviews, but things are badly backed up there. I am currently working on a revamp of native code stuff along with a bunch of new code gen things. In any case, the backlog is a known problem that is bad and it is clear to me that "the answer" is to create a better process, so hopefully we can get that all sorted out soon.

**Comment by jessitron** [comment]
@rgrempel is exactly right. I changed the native code to return asyncFunction instead of succeeding directly, like his library does, and then multiple uses of the same Effect resulted in multiple calls to the outside world.

code: https://github.com/jessitron/try-elm-cookie/tree/example-solved
