### ISSUE TITLE
Consider renaming Effects.task to Effects.fromTask

### ISSUE THREAD

**Issue by Dedoig** [evancz/elm-effects#23]
... that way it is consistent with `Effects.toTask`.  

As it stands, and specially if used unqualified as `task`, it is a confusing name.

**Comment by evancz** [comment]
I would recommend never using things unqualified.

`toTask` is not actually the "inverse" of this, so I think `fromTask` would be relatively misleading. I think this ended up getting discussed in some other thread, so I'm gonna close it here.
