### ISSUE TITLE
Effects.asyncTask

### ISSUE THREAD

**Issue by laszlopandy** [evancz/elm-effects#33]
I came across a case where I need to do two effects on startup. The first task launches an http request, and the second starts a timer to wait 5 seconds before advancing a slideshow.
```elm
type MyAction = HttpLoadSuccess String | HttpLoadFailure | AdvanceSlideshow

-- initialEffects to be used in StartApp.start { init = (..., initialEffects), ... }
initialEffects : Effects MyAction
initialEffects = Effects.batch [ httpEffect, advanceSlideshowEffect ]

advanceSlideshowEffect : Effects MyAction
advanceSlideshowEffect =
    Effects.task <| Task.sleep 1000 `Task.andThen` (\_ -> Task.succeed AdvanceSlideshow)

httpEffect : Effects MyAction
httpEffect =
    Http.getString myUrl
        |> Task.map (\data -> HttpLoadSuccess data)
        |> (flip Task.onError) (\_ -> Task.succeed HttpLoadFailure)
        |> Effects.task

```

The problem is that `Effects.batch` execute the effects in sequential order. This means that my timer will not start until after the http request has finished. I thought I had a solution using `Task.spawn`:
```elm
...
httpEffect : Effects MyAction
httpEffect =
    Http.getString myUrl
        |> Task.map (\data -> HttpLoadSuccess data)
        |> (flip Task.onError) (\_ -> Task.succeed HttpLoadFailure)
        |> Task.spawn
        |> Effects.task
```
This will make my `httpEffect` task return immediately (while the request proceeds async), but now my loaded data disappears, and my types don't match (`httpEffect : Effects Task.ThreadID`).

What I need is an Effects function which can spawn an async task, and still forward the task's final value to my update function:
```elm
Effects.asyncTask : Task x a -> Effects a
```

**Comment by laszlopandy** [comment]
Or maybe we just need a version of `Effects.batch` which runs things in parallel? What if we had:
```elm
Effects.sequence : List (Effects a) -> Effects a
Effects.parallel : List (Effects a) -> Effects a
```

**Comment by laszlopandy** [comment]
I checked the code, and it looks like it does run them in parallel using Task.spawn:
https://github.com/evancz/elm-effects/blob/master/src/Effects.elm#L190

I think we should update the documentation to make it clear that they are running parallel and the actions could come in a different order.

**Comment by evancz** [comment]
I believe we already have `Task.sequence` and I am expecting to have `Task.interleave` and `Task.race` in the next release of core. I agree about making it clearer that things run concurrently (not the same as parallel) but I'm not sure it makes sense to worry too much about this with the 0.17 things on the way.

**Comment by laszlopandy** [comment]
I don't know how far away you think 0.17 is, but probably we should have a release of at least core and elm-effects before then.

**Comment by evancz** [comment]
Perhaps. I guess do a PR that changes the docs how you want them for this topic in the meantime and we can do a patch?
