### ISSUE TITLE
General "tabs" component

### ISSUE THREAD

**Issue by vilterp** [evancz/elm-effects#4]
Has anyone tried to make a reusable tabbed container with this API yet? I.e. something which contains a list of other components, which we switch between with tabs? I don't think I have time for this right now, but would love to see how it would work out — it would also be a test of the flexibility of our API and would be a nice thing to have in a package. @TheSeamau5, I saw a tab thing from you on the list earlier which was cool.

**Comment by evancz** [comment]
I can't create this as part of this library, so I'm going to close this issue.
