### ISSUE TITLE
Cannot compile on Windows

### ISSUE THREAD

**Issue by jinjor** [evancz/elm-effects#9]
`elm-make` fails compiling `elm-effects` on my environment (Win7, ja, Shift-JIS).
```
[                                                  ] - 0 / 4elm-make.exe: elm-stuff\packages\evancz\elm-effects\1.0.0\sr
c\Effects.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make.exe: thread blocked indefinitely in an MVar operation
```

This may caused by following.
- https://github.com/elm-lang/elm-make/issues/33 Default encoding is not always UTF-8

For my environment, removing the following line will fix it.
https://github.com/evancz/elm-effects/blob/master/src/Effects.elm#L59

**Comment by evancz** [comment]
Awww, do you mind opening a PR that switches the quotes out for the normal `"` quotes? That'd fix it.

**Comment by evancz** [comment]
Okay, try removing `elm-stuff/` and installing again.
